### ISSUE TITLE
Support VASTAdTagURI>

### ISSUE THREAD

**Issue by supersh86** [radiantmediaplayer/rmp-vast#17]
I thoroughly examined the XML of my source and noticed that it produces a list of other external XML.
The tag is called VASTAdTagURI.
And if we go there, there will already be MediaFiles
can you please support this tag?

**Comment by radiantmediaplayer** [comment]
Thanks but we have been supporting the VASTAdTagURI tag since the first release of rmp-vast. If you are having an issue playing a VAST tag through rmp-vast please provide a publicly available VAST URL and player code that reproduce your issue so we can have a look at it.

**Comment by radiantmediaplayer** [comment]
closing as no more information available at this time.
