### ISSUE TITLE
VAST 3 ad pod skipoffset not working if given as percentage

### ISSUE THREAD

**Issue by henryschmieder** [radiantmediaplayer/rmp-vast#24]
working fine :  `<Linear skipoffset="00:00:05">`

not working : `<Linear skipoffset="20%">`

example: http://projects.kaltura.com/MichalR/vast3_demo.xml

**Comment by radiantmediaplayer** [comment]
Fixed in [2.4.13](https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v2.4.13)
