### ISSUE TITLE
pause event fired when the ad ends

### ISSUE THREAD

**Issue by chanand** [radiantmediaplayer/rmp-vast#26]
Once the ad ends a `pause` event is fired before the `complete` event.

This can be reproduced with the example too:
https://www.radiantmediaplayer.com/rmp-vast/app/

![image](https://user-images.githubusercontent.com/1317789/87871775-0d284900-c9bc-11ea-92ca-68c496054596.png)

**Comment by radiantmediaplayer** [comment]
Hi,
This is normal expected behaviour. Some browsers produce a "pause" event just before the "ended" event for HTML5 video. This is not something we would consider bypassing in rmp-vast as it would introduce overhead code.
Thanks
Arnaud
