### ISSUE TITLE
shaka support

### ISSUE THREAD

**Issue by mihaiav** [radiantmediaplayer/rmp-vast#27]
Is there any plugin for Shaka player? We are using shaka to play our video content and although shaka provides integration for google ima [0] we would love to use an open source VAST plugin/player instead of Google IMA.

> Custom Ad Manager Implementations
  architecture supports custom ad manager implementations. Every ad manager should implement the shaka.extern.IAdManager interface. To make the player use a custom ad manager implementation, invoke the code to set it before instantiating the player.

// myapp.CustomAdManager is a placeholder name for your ad manager implementation.
shaka.Player.setAdManagerFactory(() => new myapp.CustomAdManager());

[0] https://shaka-player-demo.appspot.com/docs/api/tutorial-ad_monetization.html

**Comment by radiantmediaplayer** [comment]
Hi,
We do not have such plugin. We are using rmp-vast with Shaka player for DASH streaming in Radiant Media Player but it does not rely on the Shaka player interface you mentioned as this interface did not exist when we started our implementation. Right now you need to use rmp-vast and Shaka player without that interface and rely on Shaka and rmp-vast respective API to sync ad and content playback.
