### ISSUE TITLE
Check for this.container before querySelector call

### ISSUE THREAD

**Issue by mcmimik** [radiantmediaplayer/rmp-vast#29]
When searching for a `container` element by id, it may not exist and return `null`, so when searching for a `contentWrapper` element (line 26), _querySelector_ may cause an exception:

https://github.com/radiantmediaplayer/rmp-vast/blob/3f2e216d1fda7b3dbac1c7cc0158ca8266712886/js/src/module.js#L25-L33

Maybe it would be more reliable to check for `this.container === null` before `contentWrapper` assignment.

**Comment by radiantmediaplayer** [comment]
Hi,
Thanks for bringing this to our attention. I will fix this for the next release.

**Comment by radiantmediaplayer** [comment]
Fixed in [v3.0.0](https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v3.0.0)
