### ISSUE TITLE
setMute not working

### ISSUE THREAD

**Issue by brunonrosa** [radiantmediaplayer/rmp-vast#30]
I created an unmute button for users to click since the video is set to autoplay. This click triggers the setMute(false) function. Unfortunately it's not working. I made it work once... i do not know what happened.

**Comment by radiantmediaplayer** [comment]
The setMute API seems to be working for me at our demo page https://www.radiantmediaplayer.com/rmp-vast/app/. We cannot help with user-specific implementation, only with rmp-vast core library issues. You should review the demo app in at app/index.html.
