### ISSUE TITLE
Insecure mode not working with Latest release of google chrome (Version 91.0.4472.101)

### ISSUE THREAD

**Issue by mouchii** [radiantmediaplayer/rmp-vast#37]
Hello,

With the latest google chrome version (91.0.4472.101), the insecure mode for Google IMA is broken. (https://groups.google.com/g/ima-sdk/c/-D3V3oEI9Rw)
We have the same issue with RMP vast, are you aware of it ?

Regards,

**Comment by mouchii** [comment]
This problem happened only with VPAID.

**Comment by mouchii** [comment]
Hi,

We found the problem on chrome reporting bug.
You have just to change the src of iframe from "about:self" to "about:blank".
https://bugs.chromium.org/p/chromium/issues/detail?id=1220186

**Comment by radiantmediaplayer** [comment]
Hi, thanks for reporting. It seems this is still under review but since about:blank works cross browsers and we are now unable to display VPAID tags like IMA SDK, I have pushed about:blank in 3.2.1. We will see how it goes in the future.
