### ISSUE TITLE
Incorrect adVerifications parameters in omsdk.js

### ISSUE THREAD

**Issue by kamtungc** [radiantmediaplayer/rmp-vast#50]
Please correct omsdk.js.

Incorrect verification parameter:
    const resources = this.adVerifications.map((verification) => {
      return new VerificationScriptResource(
        verification.resource,
        verification.vendor,
        verification.verificationParameters,
        ACCESS_MODE
      );
    });

Correct verification parameter:
    const resources = this.adVerifications.map((verification) => {
      return new VerificationScriptResource(
        verification.resource,
        verification.vendor,
        verification.parameters,
        ACCESS_MODE
      );
    });

References:
rmp-vast/src/assets/@dailymotion/vast-client/src/ad_verification.js

export function createAdVerification() {
  return {
    resource: null,
    vendor: null,
    browserOptional: false,
    apiFramework: null,
    type: null,
    parameters: null,
    trackingEvents: {},
  };
}

**Comment by radiantmediaplayer** [comment]
This is fixed in [7.1.0](https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v7.1.0).
