### ISSUE TITLE
Pause event not firing at all

### ISSUE THREAD

**Issue by RaphaelLEMAS** [radiantmediaplayer/rmp-vast#52]
The "pause" event on an ad that is paused is not fired even if the "adpaused" event is correctly fired (see screenshot below):
<img width="1725" alt="Capture d’écran 2022-09-02 à 12 05 43" src="https://user-images.githubusercontent.com/52014731/188117050-63bbd2d7-cb39-4389-b1d4-f685b7fc3fee.png">

However, the "resume" event seems to be working correctly.

**Comment by Momotoculteur** [comment]
Hi,

Same issue for me !

**Comment by radiantmediaplayer** [comment]
Thank you guys for spotting that one. It is now fixed in [7.2.2](https://github.com/radiantmediaplayer/rmp-vast/releases). If you are testing on our demo page, please empty your browser cache for changes to be reflected.
