### ISSUE TITLE
How to allow auto height of the rmp-container

### ISSUE THREAD

**Issue by Tomek104104** [radiantmediaplayer/rmp-vast#56]
How to allow auto height of the rmp-container ?
sometimes video ads have 1x1 proportion, sometime 16:9
I'm trying to get always 100% width with auto height

in most of the cases VAST does not provide height so rmpVast.getAdMediaHeight() gives -1

it looks that rmp-container required declared initial, fixed value

**Comment by radiantmediaplayer** [comment]
Hi, 
See an example of implementation https://github.com/radiantmediaplayer/rmp-vast/blob/master/app/index.html.
You can set size of container with CSS or JavaScript.
If you need to change size dynamically see fullscreen handling in demo app.

**Comment by Tomek104104** [comment]
Hi
thank you for the reply
my problem is a bit different
I want to have always same width of the video ad
and height to be dynamically changed - but not full screen
when I have container 16x9 i see correctly 16:9 video
[image: image.png]
but when I have 1:1 video, video is forced in the same container
[image: image.png]
and I want to have container auto adjust in height (to get full width of
the 1x1 video)
question is if there is any way to get actual size of the video (visible
width) other then getAdMediaWidth() as this is based on video size info
provided in VAST xml (what is usually not provided)

br
Tomek

pon., 14 lis 2022 o 17:52 radiantmediaplayer ***@***.***>
napisał(a):

**Comment by radiantmediaplayer** [comment]
This is something you need to figure on your side. We do not support implementation issue.

**Comment by Tomek104104** [comment]
well, it is your library that handles VAST
my question was if there is any feedback available from your handler
so I've asked you

of course implementation is on my side
IMA SDK automatically handles this problem and shows video always fitted to
full width of the div

anyhow, thanks
I will try to play around

T

pon., 14 lis 2022 o 18:21 radiantmediaplayer ***@***.***>
napisał(a):
