### ISSUE TITLE
Implements companion ads support

### ISSUE THREAD

**Issue by radiantmediaplayer** [radiantmediaplayer/rmp-vast#6]
This would be a long-run task. Contributions are welcome.

**Comment by rohanraj7316** [comment]
@radiantmediaplayer
I would like to work on adding support for companion ads.
can you help me get started with this issue?

**Comment by radiantmediaplayer** [comment]
Hi @rohanraj7316. We do not really have the bandwidth right now to guide you into doing this but essentially you just need to learn the rmp-vast code base, the VAST 3 spec and PR this according to our coding style.

**Comment by radiantmediaplayer** [comment]
Implemented in 2.4.0
