### ISSUE TITLE
RmpVast constructor issue

### ISSUE THREAD

**Issue by roarc0** [radiantmediaplayer/rmp-vast#67]
I'm having some issues in creating the RmpVast instance inside a svelte component.

```
    // the div,video elements: rmp-{content,container,video} are created in the svelte component but using this doesn't work.
    let cont = document.getElementById(id); // returns nil
    console.log("cont", cont);

    rmpVast = new RmpVast(id, params); // so here fails.. rmp-vast.min.js:1 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

Using IMA SDK I can initialize everything using the element that is bound by svelte itself to a variable inside the component.

```
    const adDisplayContainer = new google.ima.AdDisplayContainer(adContainer, element);
    adDisplayContainer.initialize();
```

It would be nice to be able to use the HTMLELement if passed to the constructor.

**Comment by radiantmediaplayer** [comment]
Hi,
I have no experience with Svelte framework. We use the id of the player container in RmpVast constructor as follows:
```
    this.id = id;
    this.container = document.getElementById(this.id);
    this.contentWrapper = this.container.querySelector('.rmp-content');
    this.currentContentPlayer = this.container.querySelector('.rmp-video');
```
While it would technically be possible for us to pass the element in constructor instead of id, you should still be in a web environment where, window, document and other items a browser/WebView is supposed to have, so calling document.getElementById(this.id) should not be a problem. Again this might be specific to Svelte so you will need to research on Svelte docs/forum on how to access document property.

**Comment by roarc0** [comment]
Hi!
Thanks for the answer, your message makes lots of sense but still svelte is not working as expected.

I asked for an solution here: (https://www.reddit.com/r/sveltejs/comments/1eva7l8/issues_with_documentgetelementbyid/).

I wanted to use your library but this could push me to use other solutions that accept the element as input to their constructor such as: IMA and OpenPlayerJS.

**Comment by radiantmediaplayer** [comment]
Hi, with [16.1.0](https://github.com/radiantmediaplayer/rmp-vast/releases/tag/v16.1.0) release, it is now possible to pass a reference to player container when creating a new RmpVast instance. This should help with your use-case.

**Comment by radiantmediaplayer** [comment]
// We already have a reference to the player container (e.g. element with "rmp-container" class)
const element = this.element;
// create RmpVast instance
const rmpVast = new RmpVast(element, params);

**Comment by roarc0** [comment]
wow, thanks for the support!
