### ISSUE TITLE
Error 402 - Timeout of MediaFile URI ( SIMID ads on TIZEN TV )

### ISSUE THREAD

**Issue by DevOnTheBox** [radiantmediaplayer/rmp-vast#68]
I am currently testing SIMID ads using the sample code from this repo on the TIZEN TV Emulator, but I am encountering an issue where the MediaFile URI times out with the **_Error 402 - Timeout of MediaFile URI_**.

**Steps to Reproduce:**
- Copy or clone the repository into your TIZEN TV project.
- Launch ./app/index.html on the TIZEN TV Emulator.
- Use the provided SIMID test URL: https://www.radiantmediaplayer.com/vast/tags/simid.xml
- Test the ads on the TIZEN TV Emulator.
- The following error is displayed: 402 - Timeout of MediaFile URI.

**Additional Information:**
- I have confirmed that enableSimid: true is set in the params object.
- I have tried increasing the creativeLoadTimeout parameter, but the issue persists.
- I have tried it with multiple other SIMID tags.
- This error occurs specifically when running the ads on the TIZEN TV.

**Expected Behavior:**
The ad should load successfully.

**Actual Behavior:**
Error 402 - Timeout of MediaFile URI.

**Environment:**
Platform: TIZEN TV

**Screenshot:**
![image](https://github.com/user-attachments/assets/f3c2aeb9-96a7-46ff-ae41-8cfe291bc308)

**Comment by radiantmediaplayer** [comment]
Hi,
We cannot investigate issue that are on TIZEN TV Emulator. TV Emulators are known to be buggy when it comes to reading media files. 
You need to test on an actual physical TIZEN TV 4+ device.
Also note that SIMID support in smart TVs is nascent, so interactivity could be limited.
If you can reproduce your issue on an actual physical device, please provide the details of the device tested and we will have a look.
